### ISSUE TITLE
感谢以及一个建议

### ISSUE THREAD

**Issue by Haocen2004** [tomzhu1024/bedrock-server-libraries#1]
感谢老哥分享
以及希望可以照顾下部分用户的网络环境
把仓库移到国内
比如说码云 gitee.com
虽然说码云已经有镜像了，不过看起来不是你传的

**Comment by tomzhu1024** [comment]
嗯嗯，了解了
不过去看了一下确实已经有镜像了，如果之后有更新，会考虑一下多传一份到国内站点的
